export const data= [
    {id:1,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:2,title:"chapeau",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:3,title:"casquette",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:4,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:5,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:6,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:7,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:8,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:9,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:10,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:11,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:12,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:13,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:14,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:15,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:16,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:17,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:18,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:19,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:20,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:21,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:22,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:23,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
    {id:24,title:"Bob",content:"La coif qui vous donnera un vrai style !",srcImage:"bob",price:20},
]